version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securedb
      MYSQL_USER: user
      MYSQL_PASSWORD: passer@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8085:80"  # Change this line to map port 8085 on your host to port 80 in the container
    depends_on:
      - db

volumes:
  db_data:
